// Wedding / event invitation portfolio — auto-categorised
// Price = base package price in INR. Edit PRICES to change everything at once.
// groom/bride order is assumed from URL order (first name = groom) — items with review:true need a quick check
// dup:true  = duplicate / variant URL of another entry (hide from public showcase)
// review:true = religion category guessed from names, please verify
// hero 1-5  = hero image slot (cycled); 0 = not featured

const PRICES = {
  "Nikah": 2499, "Hindu": 2499, "Christian": 2499,
  "Engagement": 1999, "Reception": 1499, "Housewarming": 1499,
  "Pre-wedding Ritual": 1499, "Business/Tool": 0, "Sample/Test": 0
};

const CATEGORIES = ["Nikah","Hindu","Christian","Engagement","Reception","Housewarming","Pre-wedding Ritual"];

const SAMPLES = [
 {bride:"Naja", groom:"Rahoof", cat:"Nikah", price:2499, url:"https://rahoof-naja.vercel.app/", hero:1},
 {bride:"Adheela", groom:"Ajil", cat:"Nikah", price:2499, url:"https://ajil-adheela.vercel.app/", hero:2},
 {bride:"Nena", groom:"Amar", cat:"Hindu", price:2499, url:"https://amar-nena.vercel.app/", hero:3, review:true},
 {bride:"Sandra", groom:"Anoop", cat:"Hindu", price:2499, url:"https://anoop-sandra.vercel.app/", hero:4},
 {bride:"Arya", groom:"Aswanth", cat:"Hindu", price:2499, url:"https://aswanth-arya.vercel.app/", hero:5},
 {bride:"Hardeep", groom:"Drishya", cat:"Hindu", price:2499, url:"https://drishya-hardeep.vercel.app/", hero:2},
 {bride:"Mariya", groom:"Jobin", cat:"Engagement", price:1999, url:"https://jobin-mariya-betrothal.vercel.app/", hero:0, review:true},
 {bride:"Liyana", groom:"Irfan", cat:"Nikah", price:2499, url:"https://irfan-liyana.vercel.app/", hero:3},
 {bride:"Mariya", groom:"Jobin", cat:"Christian", price:2499, url:"https://jobin-mariya.vercel.app/", hero:4},
 {bride:"Raisha", groom:"Khaleel", cat:"Nikah", price:2499, url:"https://khaleel-raisha.vercel.app/", hero:5},
 {bride:"Aleena", groom:"Jino", cat:"Christian", price:2499, url:"https://jino-aleena.vercel.app/", hero:1},
 {bride:"Jesna", groom:"Aljith", cat:"Christian", price:2499, url:"https://jesna-aljith.vercel.app/", hero:2, review:true},
 {bride:"Niveditha", groom:"Aravind", cat:"Hindu", price:2499, url:"https://aravind-niveditha.vercel.app/", hero:3},
 {bride:"Fairuz", groom:"Rizwan", cat:"Nikah", price:2499, url:"https://rizwan-fairuz.vercel.app/", hero:4},
 {bride:"Noohulhakh", groom:"Shafi", cat:"Nikah", price:2499, url:"https://shafi-noohulhakh.vercel.app/", hero:2},
 {bride:"Adheela", groom:"Ajil", cat:"Nikah", price:2499, url:"https://adheela-ajil.vercel.app/", hero:0, dup:true},
 {bride:"Fidha", groom:"Hamras", cat:"Nikah", price:2499, url:"https://hamras-fidha.vercel.app/", hero:2},
 {bride:"Devika", groom:"Nahal", cat:"Hindu", price:2499, url:"https://nahal-devika.vercel.app/", hero:4, review:true},
 {bride:"Yukta", groom:"Rahul", cat:"Hindu", price:2499, url:"https://rahul-yukta.vercel.app/", hero:5},
 {bride:"", groom:"Skill Up Learning Academy", cat:"Business/Tool", price:0, url:"https://www.skilluplearningacademy.in/", hero:0, review:true},
 {bride:"Safa", groom:"Afnan", cat:"Nikah", price:2499, url:"https://safa-afnan-kvmq.vercel.app/", hero:0, dup:true},
 {bride:"Safa", groom:"Roshan", cat:"Nikah", price:2499, url:"https://roshan-safa.vercel.app/", hero:3, review:true},
 {bride:"Maryam", groom:"Ajeer", cat:"Nikah", price:2499, url:"https://maryam-ajeer.vercel.app/", hero:4, review:true},
 {bride:"Mansi", groom:"Theja", cat:"Hindu", price:2499, url:"https://theja-mansi-hindi.vercel.app/", hero:0, dup:true},
 {bride:"Mansi", groom:"Theja", cat:"Hindu", price:2499, url:"https://theja-mansi.vercel.app/", hero:5},
 {bride:"Tejal", groom:"Sebastian", cat:"Christian", price:2499, url:"https://sebastian-tejal-wedding-yy2d.vercel.app/", hero:0, dup:true},
 {bride:"Mansi", groom:"Theja", cat:"Hindu", price:2499, url:"https://mansi-theja.vercel.app/", hero:0, dup:true},
 {bride:"Najma", groom:"Shaheer", cat:"Nikah", price:2499, url:"https://shaheer-najma.vercel.app/", hero:1},
 {bride:"Rishda", groom:"Shabeeb", cat:"Nikah", price:2499, url:"https://shabeeb-rishda.vercel.app/", hero:3},
 {bride:"Farira", groom:"Sabrudeen", cat:"Nikah", price:2499, url:"https://farira-sabrudeen-1.vercel.app/", hero:0, dup:true},
 {bride:"Farira", groom:"Sabrudeen", cat:"Nikah", price:2499, url:"https://sabrudeen-farira.vercel.app/", hero:5},
 {bride:"Aqila", groom:"Nihal", cat:"Nikah", price:2499, url:"https://aqila-nihal.vercel.app/", hero:0, dup:true},
 {bride:"Irin", groom:"Joji", cat:"Christian", price:2499, url:"https://joji-irin.vercel.app/", hero:2},
 {bride:"Aiswarya", groom:"Justin", cat:"Christian", price:2499, url:"https://justin-aiswarya.vercel.app/", hero:3, review:true},
 {bride:"Liza", groom:"Benz", cat:"Christian", price:2499, url:"https://benz-liza.vercel.app/", hero:4},
 {bride:"", groom:"Image Convert Tool", cat:"Business/Tool", price:0, url:"https://image-convert-delta.vercel.app/", hero:0, review:true},
 {bride:"Krishnendhu", groom:"Hariprasad", cat:"Hindu", price:2499, url:"https://hariprasad-krishnendhu.vercel.app/", hero:1},
 {bride:"Lilly", groom:"Gregory", cat:"Christian", price:2499, url:"https://gregory-lilly.vercel.app/", hero:2},
 {bride:"Hanna", groom:"Fadhih", cat:"Nikah", price:2499, url:"https://fadhih-hanna.vercel.app/", hero:4},
 {bride:"Rafiya", groom:"Shamnad", cat:"Nikah", price:2499, url:"https://shamnad-rafiya.vercel.app/", hero:2},
 {bride:"Aslam", groom:"Hanan", cat:"Nikah", price:2499, url:"https://hanan-aslam.vercel.app/", hero:3, review:true},
 {bride:"Anjitha", groom:"Abilash", cat:"Reception", price:1499, url:"https://abilash-anjitha-reception.vercel.app/", hero:0, review:true},
 {bride:"Swathi", groom:"Aswinlal", cat:"Hindu", price:2499, url:"https://swathi-aswinlal.vercel.app/", hero:1, review:true},
 {bride:"Aqila", groom:"Nihal", cat:"Nikah", price:2499, url:"https://nihal-aqila.vercel.app/", hero:3},
 {bride:"Anjitha", groom:"Abhilash", cat:"Hindu", price:2499, url:"https://abhilash-anjitha.vercel.app/", hero:4},
 {bride:"Amrutha", groom:"Sarath", cat:"Hindu", price:2499, url:"https://sarath-amrutha.vercel.app/", hero:5},
 {bride:"Merin Mavelil", groom:"Rohith Reji", cat:"Christian", price:2499, url:"https://rohith-reji-merin-mavelil.vercel.app/", hero:2},
 {bride:"", groom:"Homezo", cat:"Business/Tool", price:0, url:"https://homezo.vercel.app/", hero:0, review:true},
 {bride:"Rosina", groom:"Ajmal", cat:"Nikah", price:2499, url:"https://ajmal-rosina.vercel.app/", hero:4},
 {bride:"Divya", groom:"Mira", cat:"Hindu", price:2499, url:"https://mira-divya.vercel.app/", hero:5, review:true},
 {bride:"Shifana", groom:"Nishal", cat:"Nikah", price:2499, url:"https://shifana-nishal.vercel.app/", hero:4, review:true},
 {bride:"Bhagya", groom:"Sreehari", cat:"Hindu", price:2499, url:"https://sreehari-bhagya.vercel.app/", hero:5},
 {bride:"Bismida", groom:"Ajmal", cat:"Nikah", price:2499, url:"https://ajmal-bismida.vercel.app/", hero:1},
 {bride:"Jeslin", groom:"Jen", cat:"Christian", price:2499, url:"https://jen-jeslin.vercel.app/", hero:3},
 {bride:"Merlymol", groom:"Nikhil", cat:"Christian", price:2499, url:"https://merlymol-nikhil.vercel.app/", hero:2, review:true},
 {bride:"Ayisha", groom:"Fayas", cat:"Nikah", price:2499, url:"https://ayisha-fayas.vercel.app/", hero:3, review:true},
 {bride:"", groom:"Muhammed & Jasheera", cat:"Housewarming", price:1499, url:"https://house-warming-muhammed-jasheera.vercel.app/", hero:0},
 {bride:"Sneha", groom:"Thomas", cat:"Christian", price:2499, url:"https://thomas-sneha.vercel.app/", hero:4, review:true},
 {bride:"Rifana", groom:"Rafnas", cat:"Nikah", price:2499, url:"https://rafnas-rifana.vercel.app/", hero:5},
 {bride:"Anitta", groom:"Eldhos", cat:"Christian", price:2499, url:"https://eldhos-anitta.vercel.app/", hero:2},
 {bride:"Fathima Thanveera", groom:"Mubashir Rasin", cat:"Nikah", price:2499, url:"https://mubashir-rasin-fathima-thanveera.vercel.app/", hero:3, review:true},
 {bride:"Skenllps", groom:"Weddingcard4", cat:"Sample/Test", price:0, url:"https://weddingcard4-skenllps-projects.vercel.app/", hero:0},
 {bride:"Nesrin", groom:"Salid", cat:"Nikah", price:2499, url:"https://salid-nesrin.vercel.app/", hero:2, review:true},
 {bride:"Vafa", groom:"Afzal", cat:"Nikah", price:2499, url:"https://afzal-vafa.vercel.app/", hero:3},
 {bride:"Risa", groom:"Haseeb", cat:"Nikah", price:2499, url:"https://haseeb-risa.vercel.app/", hero:1},
 {bride:"Bigil", groom:"Surya", cat:"Hindu", price:2499, url:"https://surya-bigil.vercel.app/", hero:2, review:true},
 {bride:"", groom:"SKEN LLP (agency home)", cat:"Business/Tool", price:0, url:"https://skenllp.vercel.app/", hero:0, review:true},
 {bride:"Riyanasrin", groom:"Azarudeen", cat:"Nikah", price:2499, url:"https://riyanasrin-azarudeen.vercel.app/", hero:5, review:true},
 {bride:"Nisha", groom:"Gladson", cat:"Christian", price:2499, url:"https://gladson-nisha.vercel.app/", hero:1},
 {bride:"Anupa", groom:"Harikrishnan", cat:"Hindu", price:2499, url:"https://anupa-harikrishnan.vercel.app/", hero:2, review:true},
 {bride:"Souparnika", groom:"Balu", cat:"Hindu", price:2499, url:"https://balu-souparnika.vercel.app/", hero:1},
 {bride:"Asmiya", groom:"Zameel", cat:"Nikah", price:2499, url:"https://zameel-asmiya.vercel.app/", hero:3},
 {bride:"Anju", groom:"Basil", cat:"Christian", price:2499, url:"https://basil-anju.vercel.app/", hero:2, review:true},
 {bride:"Athiraj", groom:"Sarathraj", cat:"Hindu", price:2499, url:"https://athiraraj-sarathraj.vercel.app/", hero:5, review:true},
 {bride:"Chinchu", groom:"Lalu", cat:"Christian", price:2499, url:"https://lalu-chinchu.vercel.app/", hero:2, review:true},
 {bride:"Salva", groom:"Aslam", cat:"Nikah", price:2499, url:"https://aslam-salva.vercel.app/", hero:3},
 {bride:"Greeshma", groom:"Gokul", cat:"Hindu", price:2499, url:"https://gokul-greeshma-invitation.vercel.app/", hero:0, dup:true},
 {bride:"Mariya", groom:"Ribin Anon", cat:"Christian", price:2499, url:"https://ribin-anon-mariya.vercel.app/", hero:4, review:true},
 {bride:"", groom:"Darul Rahmah", cat:"Business/Tool", price:0, url:"https://darul-rahmah.vercel.app/", hero:0, review:true},
 {bride:"", groom:"Darul Rahmah", cat:"Business/Tool", price:0, url:"https://darur-rahmah.vercel.app/", hero:0, dup:true},
 {bride:"2", groom:"Sample", cat:"Sample/Test", price:0, url:"https://sample-2-five-drab.vercel.app/", hero:0},
 {bride:"Devika", groom:"Vishak", cat:"Hindu", price:2499, url:"https://vishak-devika.vercel.app/", hero:1},
 {bride:"Sruthy", groom:"Ashlin", cat:"Christian", price:2499, url:"https://ashlin-sruthy.vercel.app/", hero:3, review:true},
 {bride:"Nafeesa", groom:"Sofian", cat:"Nikah", price:2499, url:"https://nafeesa-sofian.vercel.app/", hero:4, review:true},
 {bride:"Wedding", groom:"Sample", cat:"Sample/Test", price:0, url:"https://sample-wedding-livid.vercel.app/", hero:0},
 {bride:"Sukanya", groom:"Akash", cat:"Hindu", price:2499, url:"https://akash-sukanya.vercel.app/", hero:1},
 {bride:"Riyanasrin", groom:"Azarudeen", cat:"Nikah", price:2499, url:"https://azarudeen-riyanasrin.vercel.app/", hero:4},
 {bride:"Daya", groom:"Nithin", cat:"Hindu", price:2499, url:"https://nithin-daya.vercel.app/", hero:5, review:true},
 {bride:"Sreeja", groom:"Mahesh", cat:"Hindu", price:2499, url:"https://mahesh-sreeja.vercel.app/", hero:4},
 {bride:"Shadha", groom:"Nihal", cat:"Nikah", price:2499, url:"https://nihal-shadha.vercel.app/", hero:5},
 {bride:"Krishna", groom:"Athul", cat:"Hindu", price:2499, url:"https://athul-krishna.vercel.app/", hero:1, review:true},
 {bride:"Muhsina", groom:"Safwan", cat:"Nikah", price:2499, url:"https://safwan-muhsina.vercel.app/", hero:3},
 {bride:"Anagha", groom:"Chandan", cat:"Hindu", price:2499, url:"https://chandan-anagha.vercel.app/", hero:0, dup:true},
 {bride:"Naadham", groom:"Rishi", cat:"Hindu", price:2499, url:"https://rishi-naadham.vercel.app/", hero:5, review:true},
 {bride:"Shahana", groom:"Safwan", cat:"Nikah", price:2499, url:"https://shahana-safwan.vercel.app/", hero:5, review:true},
 {bride:"Indulekha", groom:"Vijith", cat:"Hindu", price:2499, url:"https://indulekha-vijith.vercel.app/", hero:2, review:true},
 {bride:"Asha Fathima", groom:"Mashhoor", cat:"Nikah", price:2499, url:"https://mashhoor-ashafathima.vercel.app/", hero:3},
 {bride:"Iyas", groom:"Hisana", cat:"Nikah", price:2499, url:"https://hisana-iyas.vercel.app/", hero:5},
 {bride:"Sabitha", groom:"Shabeeb", cat:"Nikah", price:2499, url:"https://shabeeb-sabitha.vercel.app/", hero:4, review:true},
 {bride:"Safa", groom:"Remshad", cat:"Nikah", price:2499, url:"https://remshad-safa.vercel.app/", hero:2},
 {bride:"Mirsana", groom:"Noorul Ameen", cat:"Nikah", price:2499, url:"https://noorulameen-mirsana.vercel.app/", hero:4},
 {bride:"Hubna", groom:"Fahad", cat:"Nikah", price:2499, url:"https://fahad-hubna.vercel.app/", hero:2},
 {bride:"Nihana", groom:"Sabith", cat:"Nikah", price:2499, url:"https://sabith-nihana.skenllp.com/", hero:4},
 {bride:"Aleena", groom:"Jismon", cat:"Christian", price:2499, url:"https://jismon-aleena.vercel.app/", hero:1},
 {bride:"15", groom:"Wedding", cat:"Sample/Test", price:0, url:"https://wedding-15.vercel.app/", hero:0},
 {bride:"", groom:"Taaz Tech", cat:"Business/Tool", price:0, url:"https://taaztech.vercel.app/", hero:0, review:true},
 {bride:"Invitation", groom:"Wedding", cat:"Sample/Test", price:0, url:"https://wedding-invitation-ten-jet.vercel.app/", hero:0},
 {bride:"Skenllps", groom:"Quiet2", cat:"Sample/Test", price:0, url:"https://quiet2-skenllps-projects.vercel.app/", hero:0},
 {bride:"Ayisha Adabiyya", groom:"Swalih Rahman", cat:"Nikah", price:2499, url:"https://swalih-rahman-and-ayisha-adabiyya.vercel.app/", hero:2},
 {bride:"Sihana & Sahadiyya", groom:"Aufa & Noufal", cat:"Nikah", price:2499, url:"https://aufa-sihana-noufal-sahadiyya.vercel.app/", hero:3, review:true},
 {bride:"Afna", groom:"Ashfak", cat:"Nikah", price:2499, url:"https://ashfak-afna.vercel.app/", hero:5}
];

// Public showcase: remove dups, tools and tests
const SHOWCASE = SAMPLES.filter(s => !s.dup && s.price > 0);
const byCat = cat => SHOWCASE.filter(s => s.cat === cat);

// module.exports = { SAMPLES, SHOWCASE, PRICES, CATEGORIES };  // Node
// export { SAMPLES, SHOWCASE, PRICES, CATEGORIES };            // ES modules
