/* One entry per invitation. Add a line, redeploy — done.
   url   = live invitation link (loads inside the phone). Leave "" to show poster only.
   img   = poster image in /images (optional — if missing, the live site loads into the phone as its own preview)
   hero  = 1-5 to show in the hero fan (the middle one, 3, is the big one)
   price = optional; falls back to DEFAULT_PRICE. Set DEFAULT_PRICE to 0 to hide prices. */
const SAMPLES = [
 {bride:"Fidha", groom:"Sanoop", cat:"Nikah", price:2999, url:"https://sanoop-fidha.vercel.app/", hero:1},
 {bride:"Vibha", groom:"Jishnu", cat:"Hindu", price:2499, url:"https://jishnu-vibha.skenllp.com/", hero:2},
 {bride:"Fathima Hanna", groom:"Shanu Farhan", cat:"Nikah", price:2499, url:"https://shanu-hanna.skenllp.com/", hero:3},
 {bride:"Athira", groom:"Vinay", cat:"Hindu", price:2499, url:"https://vinay-athira-wedding.vercel.app/", hero:4},
 {bride:"Sandra", groom:"Vishnu", cat:"Hindu", price:2999, url:"", hero:5},
 {bride:"Naja", groom:"Rahoof", cat:"Wedding", price:2499, url:"https://rahoof-naja.vercel.app/"},
 {bride:"Adheela", groom:"Ajil", cat:"Wedding", price:2499, url:"https://ajil-adheela.vercel.app/"},
 {bride:"Nena", groom:"Amar", cat:"Wedding", price:2499, url:"https://amar-nena.vercel.app/"},
 {bride:"Sandra", groom:"Anoop", cat:"Wedding", price:2499, url:"https://anoop-sandra.vercel.app/"},
 {bride:"Arya", groom:"Aswanth", cat:"Wedding", price:2499, url:"https://aswanth-arya.vercel.app/"},
 {bride:"Jitha", groom:"Emil", cat:"Wedding", price:2499, url:"https://emil-jitha.vercel.app/"},
 {bride:"Hardeep", groom:"Drishya", cat:"Wedding", price:2499, url:"https://drishya-hardeep.vercel.app/"},
 {bride:"Mariya", groom:"Jobin", cat:"Engagement", price:2499, url:"https://jobin-mariya-betrothal.vercel.app/"},
 {bride:"Liyana", groom:"Irfan", cat:"Wedding", price:2499, url:"https://irfan-liyana.vercel.app/"},
 {bride:"Raisha", groom:"Khaleel", cat:"Wedding", price:2499, url:"https://khaleel-raisha.vercel.app/"},
 {bride:"Aravind", groom:"Niveditha", cat:"Wedding", price:2499, url:"https://niveditha-aravind.vercel.app/"},
 {bride:"Aleena", groom:"Jino", cat:"Wedding", price:2499, url:"https://jino-aleena.vercel.app/"},
 {bride:"Fairuz", groom:"Rizwan", cat:"Wedding", price:2499, url:"https://rizwan-fairuz.vercel.app/"},
 {bride:"Jubair", groom:"Sana", cat:"Wedding", price:2499, url:"https://sana-jubair.vercel.app/"},
 {bride:"Noohulhakh", groom:"Shafi", cat:"Wedding", price:2499, url:"https://shafi-noohulhakh.vercel.app/"},
 {bride:"Fidha", groom:"Hamras", cat:"Wedding", price:2499, url:"https://hamras-fidha.vercel.app/"},
 {bride:"Gilbert", groom:"Vineetha", cat:"Wedding", price:2499, url:"https://vineetha-gilbert.vercel.app/"},
 {bride:"Devika", groom:"Nahal", cat:"Wedding", price:2499, url:"https://nahal-devika.vercel.app/"},
 {bride:"Yukta", groom:"Rahul", cat:"Wedding", price:2499, url:"https://rahul-yukta.vercel.app/"},
 {bride:"Safa", groom:"Roshan", cat:"Wedding", price:2499, url:"https://roshan-safa.vercel.app/"},
 {bride:"Ajeer", groom:"Maryam", cat:"Wedding", price:2499, url:"https://maryam-ajeer.vercel.app/"},
 {bride:"Mansi", groom:"Theja", cat:"Wedding", price:2499, url:"https://theja-mansi-hindi.vercel.app/"},
 {bride:"Tejal", groom:"Sebastian", cat:"Wedding", price:2499, url:"https://sebastian-tejal-wedding.vercel.app/"},
 {bride:"Najma", groom:"Shaheer", cat:"Wedding", price:2499, url:"https://shaheer-najma.vercel.app/"},
 {bride:"Rishda", groom:"Shabeeb", cat:"Wedding", price:2499, url:"https://shabeeb-rishda.vercel.app/"},
 {bride:"Sabrudeen", groom:"Farira", cat:"Wedding", price:2499, url:"https://farira-sabrudeen-1.vercel.app/"},
 {bride:"Fathima", groom:"Abduraheem", cat:"Wedding", price:2499, url:"https://abduraheem-fathima.vercel.app/"},
 {bride:"Fathima", groom:"Ayoob", cat:"Wedding", price:2499, url:"https://ayoob-fathima.vercel.app/"},
 {bride:"Nihal", groom:"Aqila", cat:"Wedding", price:2499, url:"https://aqila-nihal.vercel.app/"},
 {bride:"Irin", groom:"Joji", cat:"Wedding", price:2499, url:"https://joji-irin.vercel.app/"},
 {bride:"Aiswarya", groom:"Justin", cat:"Wedding", price:2499, url:"https://justin-aiswarya.vercel.app/"},
 {bride:"Liza", groom:"Benz", cat:"Wedding", price:2499, url:"https://benz-liza.vercel.app/"},
 {bride:"Krishnendhu", groom:"Hariprasad", cat:"Wedding", price:2499, url:"https://hariprasad-krishnendhu.vercel.app/"},
 {bride:"Lilly", groom:"Gregory", cat:"Wedding", price:2499, url:"https://gregory-lilly.vercel.app/"},
 {bride:"Harsha", groom:"Aravind", cat:"Wedding", price:2499, url:"https://aravind-harsha.vercel.app/"},
 {bride:"Hanna", groom:"Fadhih", cat:"Wedding", price:2499, url:"https://fadhih-hanna.vercel.app/"},
 {bride:"Hudha", groom:"Badarudheen", cat:"Wedding", price:2499, url:"https://badarudheen-hudha.vercel.app/"},
 {bride:"Rafiya", groom:"Shamnad", cat:"Wedding", price:2499, url:"https://shamnad-rafiya.vercel.app/"},
 {bride:"Aslam", groom:"Hanan", cat:"Wedding", price:2499, url:"https://hanan-aslam.vercel.app/"},
 {bride:"Ahamedsha", groom:"Nibina", cat:"Wedding", price:2499, url:"https://nibina-ahamedsha.vercel.app/"},
 {bride:"Anjitha", groom:"Abilash", cat:"Reception", price:2499, url:"https://abilash-anjitha-reception.vercel.app/"},
 {bride:"Sharonimol", groom:"Benny", cat:"Wedding", price:2499, url:"https://benny-sharonimol.vercel.app/"},
 {bride:"Aswinlal", groom:"Swathi", cat:"Wedding", price:2499, url:"https://swathi-aswinlal.vercel.app/"},
 {bride:"Anjitha", groom:"Abhilash", cat:"Wedding", price:2499, url:"https://abhilash-anjitha.vercel.app/"},
 {bride:"Amrutha", groom:"Sarath", cat:"Wedding", price:2499, url:"https://sarath-amrutha.vercel.app/"},
 {bride:"", groom:"Rohith Reji Merin Mavelil", cat:"Wedding", price:2499, url:"https://rohith-reji-merin-mavelil.vercel.app/"},
 {bride:"Rosina", groom:"Ajmal", cat:"Wedding", price:2499, url:"https://ajmal-rosina.vercel.app/"},
 {bride:"Divya", groom:"Mira", cat:"Wedding", price:2499, url:"https://mira-divya.vercel.app/"},
 {bride:"Liya", groom:"Jeseer", cat:"Wedding", price:2499, url:"https://jeseer-liya.vercel.app/"},
 {bride:"Nishal", groom:"Shifana", cat:"Wedding", price:2499, url:"https://shifana-nishal.vercel.app/"},
 {bride:"Bhagya", groom:"Sreehari", cat:"Wedding", price:2499, url:"https://sreehari-bhagya.vercel.app/"},
 {bride:"Bismida", groom:"Ajmal", cat:"Wedding", price:2499, url:"https://ajmal-bismida.vercel.app/"},
 {bride:"Ashiq", groom:"Ajmi", cat:"Wedding", price:2499, url:"https://ajmi-ashiq.vercel.app/"},
 {bride:"Jeslin", groom:"Jen", cat:"Wedding", price:2499, url:"https://jen-jeslin.vercel.app/"},
 {bride:"Fathima", groom:"Shijil", cat:"Wedding", price:2499, url:"https://shijil-fathima.vercel.app/"},
 {bride:"Ayesha", groom:"Sajjad", cat:"Wedding", price:2499, url:"https://sajjad-ayesha.vercel.app/"},
 {bride:"Nikhil", groom:"Merlymol", cat:"Wedding", price:2499, url:"https://merlymol-nikhil.vercel.app/"},
 {bride:"Fayas", groom:"Ayisha", cat:"Wedding", price:2499, url:"https://ayisha-fayas.vercel.app/"},
 {bride:"Jasheera", groom:"Muhammed", cat:"Housewarming", price:2499, url:"https://house-warming-muhammed-jasheera.vercel.app/"},
 {bride:"Sneha", groom:"Thomas", cat:"Wedding", price:2499, url:"https://thomas-sneha.vercel.app/"},
 {bride:"Rifana", groom:"Rafnas", cat:"Wedding", price:2499, url:"https://rafnas-rifana.vercel.app/"},
 {bride:"Misriya", groom:"Nuwaid", cat:"Housewarming", price:2499, url:"https://nuwaid-misriya-housewarming.vercel.app/"},
 {bride:"", groom:"Noorudin Nihala Nihala Munavvir", cat:"Wedding", price:2499, url:"https://noorudin-nihala-nihala-munavvir.vercel.app/"},
 {bride:"Basil", groom:"Jeeva", cat:"Wedding", price:2499, url:"https://jeeva-basil.vercel.app/"},
 {bride:"Anitta", groom:"Eldhos", cat:"Wedding", price:2499, url:"https://eldhos-anitta.vercel.app/"},
 {bride:"", groom:"Mubashir Rasin Fathima Thanveera", cat:"Wedding", price:2499, url:"https://mubashir-rasin-fathima-thanveera.vercel.app/"},
 {bride:"Rishana", groom:"Salih", cat:"Wedding", price:2499, url:"https://salih-rishana.vercel.app/"},
 {bride:"Nesrin", groom:"Salid", cat:"Wedding", price:2499, url:"https://salid-nesrin.vercel.app/"},
 {bride:"Vafa", groom:"Afzal", cat:"Wedding", price:2499, url:"https://afzal-vafa.vercel.app/"},
 {bride:"Anjum", groom:"Afshan", cat:"Wedding", price:2499, url:"https://afshan-anjum.vercel.app/"},
 {bride:"", groom:"Afrid Liya Shahba", cat:"Wedding", price:2499, url:"https://afrid-liya-shahba.vercel.app/"},
 {bride:"Haris", groom:"Raihanath", cat:"Housewarming", price:2499, url:"https://raihanath-haris-housewarming.vercel.app/"},
 {bride:"Palace", groom:"Zaims", cat:"Housewarming", price:2499, url:"https://zaims-palace.vercel.app/"},
 {bride:"Risa", groom:"Haseeb", cat:"Wedding", price:2499, url:"https://haseeb-risa.vercel.app/"},
 {bride:"Bigil", groom:"Surya", cat:"Wedding", price:2499, url:"https://surya-bigil.vercel.app/"},
 {bride:"Shyne", groom:"Anupama", cat:"Wedding", price:2499, url:"https://anupama-shyne.vercel.app/"},
 {bride:"Azarudeen", groom:"Riyanasrin", cat:"Wedding", price:2499, url:"https://riyanasrin-azarudeen.vercel.app/"},
 {bride:"Nisha", groom:"Gladson", cat:"Wedding", price:2499, url:"https://gladson-nisha.vercel.app/"},
 {bride:"", groom:"Anupama Lijin Ehrj", cat:"Wedding", price:2499, url:"https://anupama-lijin-ehrj.vercel.app/"},
 {bride:"Lijin", groom:"Anupama", cat:"Wedding", price:2499, url:"https://anupama-lijin.vercel.app/"},
 {bride:"Greshma", groom:"Gokul", cat:"Wedding", price:2499, url:"https://gokul-greshma.vercel.app/"},
 {bride:"", groom:"Fakrudeen Bawa Rukiya", cat:"Wedding", price:2499, url:"https://fakrudeen-bawa-rukiya.vercel.app/"},
 {bride:"Souparnika", groom:"Balu", cat:"Wedding", price:2499, url:"https://balu-souparnika.vercel.app/"},
 {bride:"Nygin", groom:"Merin", cat:"Wedding", price:2499, url:"https://merin-nygin.vercel.app/"},
 {bride:"Zameel", groom:"Asmiya", cat:"Wedding", price:2499, url:"https://asmiya-zameel.vercel.app/"},
 {bride:"Sanaa", groom:"Anas", cat:"Wedding", price:2499, url:"https://anas-sanaa.vercel.app/"},
 {bride:"Anju", groom:"Basil", cat:"Wedding", price:2499, url:"https://basil-anju.vercel.app/"},
 {bride:"Rinshi", groom:"Imthiyas", cat:"Wedding", price:2499, url:"https://imthiyas-rinshi.vercel.app/"},
 {bride:"Husna", groom:"Shafeeque", cat:"Wedding", price:2499, url:"https://shafeeque-husna.vercel.app/"},
 {bride:"Sarathraj", groom:"Athiraraj", cat:"Wedding", price:2499, url:"https://athiraraj-sarathraj.vercel.app/"},
 {bride:"Ashif", groom:"Nimshiya", cat:"Wedding", price:2499, url:"https://nimshiya-ashif.vercel.app/"},
 {bride:"Chinchu", groom:"Lalu", cat:"Wedding", price:2499, url:"https://lalu-chinchu.vercel.app/"},
 {bride:"Salva", groom:"Aslam", cat:"Wedding", price:2499, url:"https://aslam-salva.vercel.app/"},
 {bride:"Greeshma", groom:"Gokul", cat:"Wedding", price:2499, url:"https://gokul-greeshma-invitation.vercel.app/"},
 {bride:"", groom:"Ribin Anon Mariya", cat:"Wedding", price:2499, url:"https://ribin-anon-mariya.vercel.app/"},
 {bride:"Rahmah", groom:"Darul", cat:"Wedding", price:2499, url:"https://darul-rahmah.vercel.app/"},
 {bride:"Ishla", groom:"Raheed", cat:"Wedding", price:2499, url:"https://raheed-ishla.vercel.app/"},
 {bride:"Devika", groom:"Vishak", cat:"Wedding", price:2499, url:"https://vishak-devika.vercel.app/"},
 {bride:"Ashni", groom:"Joyel", cat:"Wedding", price:2499, url:"https://joyel-ashni.vercel.app/"},
 {bride:"Sruthy", groom:"Ashlin", cat:"Wedding", price:2499, url:"https://ashlin-sruthy.vercel.app/"},
 {bride:"Sofian", groom:"Nafeesa", cat:"Wedding", price:2499, url:"https://nafeesa-sofian.vercel.app/"},
 {bride:"", groom:"Jabir Nishila Jamsheer Jazila", cat:"Wedding", price:2499, url:"https://jabir-nishila-and-jamsheer-jazila.vercel.app/"},
 {bride:"Sukanya", groom:"Akash", cat:"Wedding", price:2499, url:"https://akash-sukanya.vercel.app/"},
 {bride:"Ameer", groom:"Fousiya", cat:"Wedding", price:2499, url:"https://fousiya-ameer-cdd7.vercel.app/"},
 {bride:"Fatema", groom:"Ayoob", cat:"Wedding", price:2499, url:"https://ayoob-fatema.vercel.app/"},
 {bride:"Daya", groom:"Nithin", cat:"Wedding", price:2499, url:"https://nithin-daya.vercel.app/"},
 {bride:"Mary", groom:"Sanju", cat:"Wedding", price:2499, url:"https://sanju-mary.vercel.app/"},
 {bride:"", groom:"Jalib Vaikkileri Fathima M C", cat:"Wedding", price:2499, url:"https://jalib-vaikkileri-fathima-m-c.vercel.app/"},
 {bride:"Sona", groom:"Alwin", cat:"Wedding", price:2499, url:"https://alwin-sona.vercel.app/"},
 {bride:"Sreeja", groom:"Mahesh", cat:"Wedding", price:2499, url:"https://mahesh-sreeja.vercel.app/"},
 {bride:"Shadha", groom:"Nihal", cat:"Wedding", price:2499, url:"https://nihal-shadha.vercel.app/"},
 {bride:"Krishna", groom:"Athul", cat:"Wedding", price:2499, url:"https://athul-krishna.vercel.app/"},
 {bride:"Muhsina", groom:"Safwan", cat:"Wedding", price:2499, url:"https://safwan-muhsina.vercel.app/"},
 {bride:"Anagha", groom:"Chandan", cat:"Wedding", price:2499, url:"https://chandan-anagha.vercel.app/"},
 {bride:"Naadham", groom:"Rishi", cat:"Wedding", price:2499, url:"https://rishi-naadham.vercel.app/"},
 {bride:"Shadiya", groom:"Jafersadiq", cat:"Wedding", price:2499, url:"https://jafersadiq-shadiya.vercel.app/"},
 {bride:"Mareena", groom:"Bestin", cat:"Wedding", price:2499, url:"https://bestin-mareena.vercel.app/"},
 {bride:"Arif", groom:"Nahda", cat:"Wedding", price:2499, url:"https://nahda-arif.vercel.app/"},
 {bride:"Safwan", groom:"Shahana", cat:"Wedding", price:2499, url:"https://shahana-safwan.vercel.app/"},
 {bride:"Zainul", groom:"Henna", cat:"Wedding", price:2499, url:"https://henna-zainul.vercel.app/"},
 {bride:"Sneha", groom:"Jeffin", cat:"Wedding", price:2499, url:"https://jeffin-sneha.vercel.app/"},
 {bride:"", groom:"Salwa Sameeha Zainul", cat:"Wedding", price:2499, url:"https://salwa-sameeha-zainul.vercel.app/"},
 {bride:"", groom:"Zainul Abid Henna Salam", cat:"Wedding", price:2499, url:"https://zainul-abid-henna-salam.vercel.app/"},
 {bride:"Vijith", groom:"Indulekha", cat:"Wedding", price:2499, url:"https://indulekha-vijith.vercel.app/"},
 {bride:"Ashafathima", groom:"Mashhoor", cat:"Wedding", price:2499, url:"https://mashhoor-ashafathima.vercel.app/"},
 {bride:"Iyas", groom:"Hisana", cat:"Wedding", price:2499, url:"https://hisana-iyas.vercel.app/"},
 {bride:"", groom:"Hisana Iyas Qysp", cat:"Wedding", price:2499, url:"https://hisana-iyas-qysp.vercel.app/"},
 {bride:"", groom:"Hisana Iyas Ctlb", cat:"Wedding", price:2499, url:"https://hisana-iyas-ctlb.vercel.app/"},
 {bride:"Sam", groom:"Shani", cat:"Wedding", price:2499, url:"https://shani-sam.vercel.app/"},
 {bride:"Remshad", groom:"Safa", cat:"Wedding", price:2499, url:"https://safa-remshad.vercel.app/"},
 {bride:"Sabitha", groom:"Shabeeb", cat:"Wedding", price:2499, url:"https://shabeeb-sabitha.vercel.app/"},
 {bride:"Vinaya", groom:"Christy", cat:"Wedding", price:2499, url:"https://christy-vinaya.vercel.app/"},
 {bride:"Thaniya", groom:"Shibili", cat:"Wedding", price:2499, url:"https://shibili-thaniya.vercel.app/"},
 {bride:"Suhail", groom:"Hamidasherin", cat:"Wedding", price:2499, url:"https://hamidasherin-suhail.vercel.app/"},
 {bride:"Thafseera", groom:"Riswan", cat:"Wedding", price:2499, url:"https://riswan-thafseera.vercel.app/"},
 {bride:"Thafseera", groom:"Riswana", cat:"Wedding", price:2499, url:"https://riswana-thafseera.vercel.app/"},
 {bride:"", groom:"Aysha Naja Mhd Ashfaq", cat:"Wedding", price:2499, url:"https://aysha-naja-mhd-ashfaq.vercel.app/"},
 {bride:"Haseema", groom:"Ajmal", cat:"Wedding", price:2499, url:"https://ajmal-haseema.vercel.app/"},
 {bride:"Sufair", groom:"Askar", cat:"Wedding", price:2499, url:"https://askar-sufair.skenllp.com/"},
 {bride:"Nafia", groom:"Bilal", cat:"Wedding", price:2499, url:"https://bilal-nafia.vercel.app/"},
 {bride:"Shanu", groom:"Hanna", cat:"Wedding", price:2499, url:"https://hanna-shanu.skenllp.com/"},
 {bride:"Mirsana", groom:"Noorulameen", cat:"Wedding", price:2499, url:"https://noorulameen-mirsana.vercel.app/"},
 {bride:"", groom:"Sanjo Rose Mary", cat:"Wedding", price:2499, url:"https://sanjo-rose-mary.vercel.app/"},
 {bride:"Hubna", groom:"Fahad", cat:"Wedding", price:2499, url:"https://fahad-hubna.vercel.app/"},
 {bride:"", groom:"Shaheer Shifna Ameena Jasir", cat:"Wedding", price:2499, url:"https://shaheer-shifna-and-ameena-jasir.vercel.app/"},
 {bride:"Anfal", groom:"Thooba", cat:"Wedding", price:2499, url:"https://thooba-anfal.vercel.app/"},
 {bride:"Salma", groom:"Rashid", cat:"Wedding", price:2499, url:"https://rashid-salma.skenllp.com/"},
 {bride:"Nihana", groom:"Sabith", cat:"Wedding", price:2499, url:"https://sabith-nihana.skenllp.com/"},
 {bride:"Afeef", groom:"Thamanna", cat:"Wedding", price:2499, url:"https://thamanna-afeef.vercel.app/"},
 {bride:"Aleena", groom:"Jismon", cat:"Wedding", price:2499, url:"https://jismon-aleena.vercel.app/"},
 {bride:"", groom:"Swalih Rahman Ayisha Adabiyya", cat:"Wedding", price:2499, url:"https://swalih-rahman-and-ayisha-adabiyya.vercel.app/"},
 {bride:"", groom:"Aufa Sihana Noufal Sahadiyya", cat:"Wedding", price:2499, url:"https://aufa-sihana-noufal-sahadiyya.vercel.app/"},
 {bride:"Karthika", groom:"Jishnu", cat:"Wedding", price:2499, url:"https://jishnu-karthika.skenllp.com/"},
 {bride:"Afna", groom:"Ashfak", cat:"Wedding", price:2499, url:"https://ashfak-afna.vercel.app/"}
];
/* How a card opens its invitation:
   "auto"   = live preview inside the phone on desktop, new tab on mobile (recommended)
   "embed"  = always load inside the phone
   "newtab" = always open in a new tab */
const MODE = "embed";
const WHATSAPP = "919207119149";
const DEFAULT_PRICE = 2499;
const PAGE_SIZE = 24;
const FEATURES = [
 ["🎨","Custom design","Made around your colours, photos and culture."],
 ["⚡","48-hr delivery","Share your reference today, get your link in 2 days."],
 ["✅","RSVP included","Guests confirm attendance right on the page."],
 ["📍","Map & directions","One-tap Google Maps for every venue."],
 ["🎵","Music","Your favourite song plays as they open it."],
 ["📸","Photo gallery","Pre-wedding photos and video in a smooth gallery."],
 ["⏳","Countdown","A live countdown to the big day."],
 ["📱","Mobile perfect","Designed for the phone it will be opened on."]
];